AllCops:
  Exclude:
    - Rakefile
    - Gemfile
    - bin/update
    - bin/rake
    - bin/setup
    - bin/yarn
    - bin/spring
    - bin/rails
    - db/seeds.rb
    - db/schema.rb
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - config/application.rb
    - config/environments/production.rb

Rails:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 11

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
